Metrics/LineLength:
  Max: 120

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/AbcSize:
  Max: 40

Metrics/MethodLength:
  CountComments: false
  Max: 19

Style/Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

RegexpLiteral:
  MaxSlashes: 0

Style/AndOr:
  Enabled: conditionals

Style/FormatString:
  Enabled: false

Style/PredicateName:
  NamePrefixBlacklist:
    - is_
    - have_